#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${API_USER} WITH PASSWORD '${API_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${API_USER};
    ALTER DATABASE ${POSTGRES_DB} OWNER TO ${API_USER};
EOSQL
